import { useState } from 'preact/hooks'
import preactLogo from './assets/preact.svg'
import viteLogo from '/vite.svg'
import './DefaultStyle.css'

export function DefaultBody(){
    return (
        <div className={"MainContent"}>
            <p>
                Lorem Ipsum
                "Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..."
                "There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain..."
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin et justo in tortor pulvinar tempus convallis sit amet est. Nulla velit tortor, tincidunt id volutpat quis, molestie eu felis. In hac habitasse platea dictumst. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec ultricies tortor commodo nisl tempor finibus. Curabitur a luctus odio. Vivamus euismod arcu magna, vitae pulvinar ipsum congue at. Fusce aliquam auctor auctor. Maecenas ac tristique arcu. Duis eros lectus, ornare non quam quis, convallis feugiat enim. Nunc ultrices aliquet dui. Aliquam tempus, turpis quis elementum pulvinar, metus lectus vestibulum tortor, ac posuere neque mi vitae odio. Maecenas sagittis orci quam, eu pharetra est feugiat at. Nunc fermentum tincidunt diam, ullamcorper finibus eros vulputate ac. Praesent sagittis purus sit amet lacus efficitur, quis pellentesque lorem vehicula.

                Morbi tempus risus tortor, id feugiat massa porta et. Donec pulvinar elementum augue nec tristique. Proin a pharetra sem. Aenean ultrices euismod eleifend. Aliquam at nisl quis augue rutrum efficitur. Maecenas id leo eget magna bibendum convallis. Maecenas ante arcu, rutrum a metus eget, maximus tempor orci. Vivamus massa lectus, dapibus id vestibulum eu, pharetra eu elit. Cras id laoreet erat, non blandit justo. Fusce urna mauris, ornare ut sollicitudin vel, accumsan et neque.

                Praesent interdum, enim quis auctor finibus, est turpis porttitor dui, volutpat rutrum ex nisi sed nulla. Sed vestibulum pretium auctor. Quisque mattis, nunc at aliquet varius, elit lacus eleifend risus, vitae pretium elit lorem venenatis tortor. Pellentesque tincidunt libero ex, in feugiat tellus auctor eu. Suspendisse ultricies, felis nec semper consectetur, tellus est porta enim, vitae scelerisque sapien nulla vel mi. Quisque tempus, ex ut porta fringilla, sem dui porta ipsum, at fringilla purus purus nec leo. Donec tempus vestibulum magna eu sodales. Duis porta turpis at ex elementum facilisis. Duis pellentesque lacinia nisi, ut scelerisque mauris dignissim quis. Fusce turpis lorem, sollicitudin non feugiat non, fermentum eget massa. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec eleifend dolor eget justo egestas, ut maximus nulla suscipit. Nulla finibus placerat mi, fringilla vulputate ipsum condimentum id. Nullam eget libero non ex rhoncus pharetra eget a arcu.

                Nam vitae ipsum quis risus imperdiet vulputate. Nunc ultrices mollis dictum. Curabitur id quam tempus, vehicula odio sed, scelerisque dui. Phasellus pharetra metus non lorem iaculis accumsan sit amet et mauris. Nulla auctor, tellus non dignissim ornare, velit diam sollicitudin lorem, a tincidunt nibh libero ac elit. Proin euismod velit non tempor blandit. Sed convallis nulla quam, ut iaculis nulla blandit vel. Duis facilisis ex sit amet turpis blandit aliquam. Donec volutpat mauris vel aliquam tincidunt. Curabitur vestibulum odio lectus, in venenatis ante lacinia nec. Vestibulum porttitor sapien lorem. Duis iaculis sapien ut lorem suscipit aliquet. Integer malesuada, nisl dictum ornare scelerisque, sem ipsum porta erat, accumsan rhoncus metus nisi quis sapien.

                Donec consectetur at justo a bibendum. Nam tristique sem ut libero aliquam elementum. Donec pellentesque orci ultrices lobortis tincidunt. Phasellus ullamcorper volutpat diam at dictum. Morbi eget libero ullamcorper ipsum facilisis blandit vel vel urna. Suspendisse porttitor quis purus a volutpat. Vestibulum id libero massa. Cras vitae condimentum metus. Nullam dictum vel metus a facilisis.

                Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Etiam hendrerit convallis turpis nec scelerisque. Nullam eu velit tempus, sagittis eros vitae, dignissim quam. Maecenas eleifend condimentum purus, sit amet vestibulum lorem cursus eget. In hac habitasse platea dictumst. Sed interdum, quam et tristique porttitor, justo tellus elementum felis, eu malesuada metus ante non lacus. Nam sed bibendum sapien. Phasellus id tincidunt purus, non sodales ligula. Vestibulum a gravida arcu. Duis velit felis, tempor eu scelerisque et, interdum at urna. Suspendisse accumsan tellus eget elit porta tempus. Quisque finibus ligula nulla, a sagittis nisi vehicula ut. Donec auctor velit metus, id euismod magna faucibus a. Pellentesque cursus, enim et pretium hendrerit, augue enim cursus enim, eu euismod nibh ante at est.

                Aliquam sit amet ante suscipit, vulputate justo sed, venenatis mauris. Cras nibh magna, vulputate eu sapien ac, porttitor ullamcorper felis. In luctus, nibh sed vestibulum pulvinar, mi nisi rutrum velit, blandit tincidunt augue eros non nisi. Maecenas lobortis interdum sodales. In euismod est vitae odio placerat, in dapibus ligula sagittis. Donec ac ipsum vitae felis accumsan pellentesque porttitor ut velit. Etiam metus libero, egestas semper venenatis ut, sagittis id leo. Vivamus nec tempor ex, at vestibulum augue. Proin aliquam lacinia quam, vel semper mauris interdum a. Aenean ac facilisis lacus, id pretium dui. Quisque sed odio in mi rhoncus laoreet. Proin felis elit, laoreet a finibus eget, cursus id eros. Phasellus a mi sit amet risus congue auctor. Donec vitae nunc consectetur, iaculis nulla iaculis, aliquet sapien. Sed quis blandit felis, varius facilisis tellus.

                Proin id mollis velit. In hendrerit risus eu mi dapibus, at porttitor nisl dignissim. Suspendisse potenti. Mauris et ligula gravida, dictum nulla at, ultrices nunc. Donec rutrum sem vel dolor euismod, ut imperdiet neque vehicula. Sed eu tortor eget urna ornare tempus eget in enim. Ut quis maximus velit, quis fringilla odio. Nulla ipsum turpis, accumsan rutrum congue in, imperdiet ut nisl. Cras sollicitudin, ligula eget condimentum vestibulum, nunc ligula maximus felis, a ultrices tellus tellus vehicula arcu. Morbi suscipit, eros at maximus congue, nisl nunc rhoncus metus, vel vehicula metus augue ac velit. Mauris sagittis interdum risus non ullamcorper. Integer at mi vel nibh dapibus tempor. Proin ut sapien volutpat, fermentum nunc id, aliquet ante. Nullam aliquet interdum dapibus. Pellentesque laoreet odio a egestas lacinia. In hac habitasse platea dictumst.

                Vestibulum vel congue augue. Ut ac nibh tincidunt, interdum metus ut, rhoncus nisi. Quisque risus nibh, malesuada id est a, imperdiet varius tellus. Aenean scelerisque hendrerit faucibus. Fusce et ante eget felis iaculis fringilla. Donec eu ex hendrerit, varius nisl vel, consequat est. Phasellus placerat, turpis vitae ornare suscipit, nisl lacus auctor ipsum, at gravida velit lacus vitae nunc. Vestibulum efficitur nibh nibh, eget consequat dui tristique ut. Vivamus condimentum libero id consequat dignissim. Sed pretium maximus elementum. Suspendisse tincidunt risus orci, eu eleifend sem maximus at. Ut cursus auctor nulla. Nulla ac consequat erat, ut tristique dui. Integer nec pretium ligula.

                Aliquam nec lacinia arcu. Duis quis felis arcu. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Pellentesque viverra sapien lorem, ac ultrices mauris dapibus nec. Cras quis vulputate ante, at dapibus mauris. Duis et dignissim ex, eu vehicula turpis. Etiam rutrum congue felis eu ultricies. Mauris sit amet sagittis arcu. Sed non nisl massa. Praesent at justo in ante commodo fermentum. Aliquam erat volutpat. Morbi eu felis ultricies, consectetur nibh eget, mollis odio. Mauris tristique dui vel purus interdum convallis. Curabitur non ex arcu.

                Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce ut orci in ante finibus efficitur. Nunc tincidunt nisi sit amet nulla sollicitudin pharetra non a felis. Fusce vel purus in purus pharetra finibus. Morbi in magna volutpat, iaculis sem vel, tristique quam. Suspendisse at lorem ultrices, tempor felis et, feugiat arcu. Vivamus mollis ac lectus sed consequat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce finibus enim in condimentum consectetur. Suspendisse euismod nunc dignissim nulla sodales pharetra. Curabitur eget augue sem. Etiam sed suscipit est, faucibus pellentesque lectus.

                Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Pellentesque erat velit, cursus ac suscipit ut, mollis et tellus. Quisque imperdiet ultrices velit sit amet dictum. Nunc elementum, velit vitae porttitor semper, lectus quam lacinia sapien, quis finibus erat felis vitae ipsum. Integer finibus libero sit amet ligula semper pellentesque. Mauris tristique dapibus pellentesque. Etiam risus leo, feugiat non enim at, dictum placerat nisl. Fusce enim odio, maximus ultrices interdum eget, condimentum ac ex. Aenean interdum blandit massa, sit amet varius metus consectetur eget. Mauris tempor dui maximus tellus molestie bibendum. Duis suscipit auctor urna ut maximus. Ut erat neque, gravida vel odio in, hendrerit mollis ante. Sed mauris felis, bibendum vitae orci at, pretium rhoncus metus.

                Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In hac habitasse platea dictumst. Duis imperdiet commodo suscipit. Quisque augue mauris, consectetur quis mi eu, ornare lobortis nisl. Proin congue urna leo, vel vestibulum augue consectetur eget. Donec euismod, lorem eu interdum lobortis, enim lectus mollis mi, in convallis ipsum sapien aliquet lacus. Mauris hendrerit ex eu magna iaculis mattis. Nullam egestas cursus lorem ac ultrices. Etiam libero urna, bibendum a ultrices quis, pulvinar ut sapien. Pellentesque sed euismod metus, sit amet tincidunt tellus. Nulla sed urna velit. Phasellus euismod ipsum nec felis feugiat, vitae pretium nisi interdum. Integer vel massa quam. Morbi pretium ut neque in porttitor. Aliquam vel libero nisi.

                Donec non scelerisque risus. Nullam malesuada, ligula in malesuada dictum, tortor nibh auctor ipsum, vitae sagittis ante nibh eu urna. Ut luctus aliquam odio, et auctor enim varius non. Proin tempor libero at ipsum iaculis, et convallis felis convallis. Praesent ac neque sodales, tempor dolor sit amet, finibus est. Nullam pretium, arcu ut fermentum eleifend, sem erat elementum lectus, non egestas est tortor quis nibh. Aliquam congue, justo non hendrerit dignissim, quam enim molestie turpis, ut varius diam urna a tortor. Maecenas auctor, risus vitae varius accumsan, dolor ex vestibulum lacus, nec pellentesque libero lectus sit amet magna. Praesent aliquam hendrerit nunc id consequat. Etiam a elit varius, condimentum mauris eget, gravida sapien. Proin sodales placerat massa in pellentesque. Proin vel ornare leo, ut aliquam tortor. Nullam egestas, arcu venenatis iaculis molestie, ex lacus dictum tortor, id mollis nulla mi vel orci. Aenean lobortis pulvinar nunc sit amet posuere. Quisque laoreet scelerisque pulvinar.

                Integer sit amet lacus non ex porta lacinia nec ut turpis. In tincidunt lacus a consectetur tempor. Vivamus nibh tortor, volutpat in libero sed, suscipit pellentesque nisl. Maecenas iaculis, neque sed ultrices hendrerit, enim metus varius nisi, a sagittis purus felis vitae nunc. Maecenas viverra tristique nulla, quis dictum ex mattis non. Cras blandit ipsum ut erat pharetra ullamcorper. Fusce eget mauris sollicitudin, placerat orci in, tincidunt nunc. Integer molestie vulputate sapien, ac rhoncus nisi porta sed. Ut aliquet ex lacus, a ultrices velit laoreet vitae. Curabitur augue ante, feugiat rhoncus mattis vitae, varius ut massa. Cras imperdiet tortor eget convallis facilisis. In hac habitasse platea dictumst. Sed et varius diam, non porta velit.

                Duis in libero quis ante dictum lobortis tincidunt id lectus. Vivamus pellentesque sed sapien ut congue. Etiam quam risus, viverra non quam in, vulputate tempor nibh. Proin ultrices gravida justo. Vestibulum in ante augue. Quisque tempor id ligula nec condimentum. Suspendisse laoreet nisl sit amet quam consectetur, eget accumsan ligula varius. Ut cursus mauris erat, elementum dignissim magna accumsan in. Quisque accumsan neque ac turpis tempor, a gravida enim tincidunt. Mauris vulputate enim vitae nisl fringilla auctor in a sapien. Ut pretium elit at nunc eleifend, sit amet aliquet eros pulvinar. Sed magna mauris, bibendum sit amet euismod eu, dignissim vel leo. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent pulvinar justo metus, vel rutrum ipsum mattis eget. Cras euismod imperdiet elit, nec molestie diam pharetra feugiat. Mauris vestibulum maximus erat, eget pretium arcu feugiat id.

                Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Maecenas sit amet luctus leo. Nullam eleifend bibendum ultrices. Vivamus congue sodales consequat. In hac habitasse platea dictumst. Fusce auctor dui sit amet mi congue, sit amet semper nunc faucibus. Morbi at sagittis elit. Duis euismod libero id mauris porta interdum.

                Morbi magna libero, placerat sed tincidunt et, pharetra a orci. Sed nec sapien vulputate, consequat sapien eget, bibendum neque. Curabitur massa lacus, tempus nec varius sed, maximus venenatis justo. Curabitur lobortis nibh est, eu rhoncus tellus auctor at. Vestibulum cursus interdum varius. Duis sed elit at nulla mollis facilisis vel sed leo. Nullam porttitor sagittis lobortis. Morbi vitae est eu sem vulputate viverra facilisis id nunc. Fusce et semper lacus. Nunc nisl libero, maximus eget lorem non, malesuada ultricies ante.

                Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Duis a tempus augue, ac placerat leo. Duis eget odio lorem. In ac leo id sapien posuere malesuada. Vestibulum tincidunt ullamcorper nibh faucibus tincidunt. Proin diam massa, vehicula non aliquam ut, vulputate ut nunc. Etiam vulputate imperdiet libero eget volutpat. Nunc faucibus non eros non accumsan. Nam iaculis tincidunt est, nec placerat diam condimentum in. Proin lacinia bibendum mauris, interdum fermentum metus mattis id. Nulla molestie libero turpis, vel commodo ipsum fringilla vel. Ut nibh nulla, iaculis ac semper id, convallis vel velit.

                Duis ut eros vestibulum, aliquam tellus sed, suscipit sapien. Aenean dapibus mauris mi, vel consectetur ante consequat sed. Etiam dapibus, lorem quis dictum accumsan, orci ligula sodales quam, quis blandit nulla enim ut est. Donec efficitur orci a mi tempus, eget consectetur ligula pretium. Nunc mollis scelerisque nisl id semper. Curabitur mattis enim eget erat sodales, id porttitor augue faucibus. Fusce vel ante nisi. Aliquam iaculis eu mauris quis blandit. Donec eget ante sapien. Nam non urna lectus.


            </p>
        </div>
    );
}